---
title: Trabajos
slug: trabajos
output:
  blogdown::html_page:
      toc: TRUE
---

# Pauta trabajo Estadística Multivariada

## Objetivo general
Aplicar los contenidos del curso a una temática de interés en formato de artículo de investigación breve.

## Sobre los temas
De modo de lograr una mayor colaboración desde el equipo docente a sus trabajos, sugerimos desarrollar los siguientes temas:

- Desigualdad social, educación cívica, justicia distributiva, opinión pública
- Estratificación social, política educativa, sociología política
- Economía laboral, relaciones laborales, acción colectiva y condiciones de empleo

Recomendamos utilizar las siguientes fuentes de datos para realizar los trabajos:

- [ELSOC](http://www.elsoc.cl/) (Ola 1)
  - [Cuestionario Ola 1](http://www.elsoc.cl/wp-content/uploads/2017/05/Cuestionario_ELSOC_Ola_01_Completo.pdf)
  - [Libro de códigos Ola 1](http://www.elsoc.cl/wp-content/uploads/2017/05/Libro_de_Codigos_ELSOC_Ola_01_Completo.pdf)
  - [base de datos Ola 1](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/0KIRBJ&version=2.0)
- [CASEN](http://observatorio.ministeriodesarrollosocial.gob.cl/casen-multidimensional/casen/basedatos.php) (evt. subset)
- [SIMCE](https://www.agenciaeducacion.cl/evaluaciones/que-es-el-simce/) (evt. subset)
- [LAPOP](https://www.vanderbilt.edu/lapop-espanol/) - OLA 2016
- [Desiguales](https://www.desiguales.org/descripcin-del-libro)
- [CEP 83 -  Módulo Desigualdad Social ISSP 2019](https://www.cepchile.cl/cep/encuestas-cep/encuestas-2009-2018/estudio-nacional-de-opinion-publica-mayo-2019)
- ISSP (International Social Survey Programme)
  - [Desigualdad Social](https://www.gesis.org/issp/modules/issp-modules-by-topic/social-inequality)
  - [Rol del Gobierno](documents/data/encuesta_cep77_jul_ago2016.zip)
  - [Orientaciones del trabajo](https://www.gesis.org/issp/modules/issp-modules-by-topic/work-orientations/2015)
- [ICTWSS](http://uva-aias.net/en/ictwss)
- Encuestas Laborales
  - [ENE](http://webanterior.ine.cl/estadisticas/laborales/ene)
  - [ESI](https://datosabiertos.ine.cl/dashboards/20610/esi/)
  - [ENUT](https://datosabiertos.ine.cl/dashboards/20612/enut/)
  - OHL, ENCLA y otras pueden ser solicitadas directamente a **Valentina Andrade**


## Modalidad de trabajo y asesorías

- Trabajo de carácter grupal
  - N° integrantes: **5 estudiantes**. Solo excepcional y justificadamente podrán ser de 4.

- **Inscripción**
  - Debe realizarse vía **u-cursos**
  - El documento debe indicar claramente integrantes, correo, tema y base de datos a utilizar
    - Es **muy** importante que el correo electrónico a señalar sea el mismo durante todo el semestre, debido a que este es central para el uso de plataformas virtuales
  - Fecha: Viernes 5 de Junio, 22.00 horas.


## Entregas

Este trabajo posee dos entregas, tal como se señala en el programa del curso

- **Entrega 1 - Trabajo Grupal** (20% de la nota final): Informe de avance. Su formato es de un borrador final de la entrega final.La idea es avanzar en todas las secciones, incluyendo la temática general a abordar así como también datos y variables en la sección de métodos, y análisis descriptivos. El énfasis en esta primera entrega se encuentra en el planteamiento de las hipótesis y el modelo de regresión asociado.

  - Incluye: estimar el modelo e interperación de este (total máximo 2000 palabras)
  
  - Consideraciones: En el caso de los trabajos donde la variable dependiente sea dicotómica, para esta primera entrega la estimación puede ser realizada preliminarmente con regresión lineal, y para la segunda se espera estimación con regresión logística

- **Entrega 2 - Trabajo Grupal** (30% de la nota final): Informe final. Su formato es de artículo/ reporte breve de investigación. En esta entrega se corrigen aspectos de la **Entrega 1**, junto con profundizar en el chequeo de supuestos, casos influyentes e interacciones

  - Incluye: todas las secciones a señalar (total máximo 3.500 palabras)

## Secciones del trabajo

1. Título: Breve, lo principal es hacer alusión al objeto central de estudio (variable dependiente) (0,5 pto)

2. Abstract (250 palabras), incluye: problema/pregunta, objetivo, datos (y N), resultado principal. (0,5 pto)

3. Introducción: definición de la problemática a abordar, su relevancia y principales conceptos (500 palabras). (2 puntos, 1 por la definición del problema y pregunta, y 1 por la definición conceptual)

- En este apartado es importante considerar:

  - Relevancia del tema de investigación
  - Relevancia del problema de investigación: además de que el "tema" pueda ser relevante (ej: aumento de desigualdad económica, disminución de niveles de participación), la relevancia del problema se refiere a cuál es el aporte distintivo de este estudio desde una perspectiva académica y disciplinar (sociología).
  - Precisar el concepto central que se va a investigar: Ejemplo "vamos a estudiar participación informal, entendiendo por ello la frecuencia de participación en actividades como marchas, boycotts y en redes sociales".
  - Precisar argumento / hipótesis central "proponemos que a medida que aumenta el nivel de contactos con identificación política de izquierda, aumenta la participación política informal"
  - El resto de la introducción usualmente se divide en dos secciones, que también son referidas como marco teórico, marco referencial, revisión bibliográfica, etc.
    - El primer apartado corresponde al objeto central de estudio /variable dependiente (explanandum), donde se profundiza en su origen y definición, y se revisan las principales investigaciones que se asocian a este concepto. (al menos 5 referencias)
    - El segundo apartado corresponde a los conceptos relacionados con las variables independientes (explanans) y en los cuales se basan las hipótesis. Se revisan en orden de relevancia. (al menos 5 referencias)

4. Objetivos / hipótesis (alrededor de 3) (250 palabras) (1 punto)

5. Metodología: datos (no olvidar número de casos), variables y métodos  (500 palabras). (3 puntos, uno por cada subsección)
- Esta sección también incluye una tabla de descriptivos básicos, y una descripción detallada de la operacionalización y medición de las variables.

6. Análisis (1500 palabras) (8 puntos)
- Comenzar con análisis descriptivo uni y bivariado, nubes de puntos, tabla de correlaciones (1 punto).
- Introducción del sentido de los modelos en relación a las hipótesis (1 punto)
- Presentación de la(s) tabla(s) (2 puntos)
- Interpretación (4 puntos).

7. Discusión de los resultados, con énfasis en la relación entre variable dependiente e independientes, limitaciones, posibles estudios futuros. (500 palabras) (3 puntos)

<div class="alert alert-info">
¡ Recordatorio !
En la **Entrega 1** deben llegar al menos a estimar un modelo de regresión e interpretarlo.

En la **Entrega 2** se incorpora la revisión de supuestos, el análisis de dos variables dependientes, y la aplicación de regresión logística para quienes analizan dependientes categóricas binarias. Tener en cuenta además las consideraciones generales respecto a la revisión 1, y por supuesto, los comentarios específicos de cada trabajo.

</div>


## Formato
- (R)Markdown: se recomienda su uso pues facilita la integración y reproducibilidad de los análisis en R (<http://rusersgroup.com/blog/rmarkdown/>).
  - Podrán encontrar una [guía básica para el uso de (R)Markdown](https://jciturras.github.io/Tutorial-rmarkdown/)
  - En sus **proyectos de RStudio Cloud** pondrán encontrar una plantilla (**Material 4 **) para realizar el trabajo en este formato para el informe final.

- Formato Tradicional: archivo .pdf en tamaño carta, letra Times New Roman, tamaño 12, interlineado 1,5, márgenes normales (2,5 cm superior e inferior, 3 cm derecho e izquierdo).
- Referencias: APA 6ta Edición o [ASA](https://www.asanet.org/sites/default/files/savvy/documents/teaching/pdfs/Quick_Tips_for_ASA_Style.pdf)

- Tablas de calidad: formato APA [(líneas horizontales y señalando fuente)](https://apastyle.apa.org/style-grammar-guidelines/tables-figures/tables).


## Fechas
Todas las entregas deben realizarse en la sección de **Tareas** de u-cursos.

- Inscripción: Viernes 5 de junio, 22.00 horas.
- Entrega 1: Viernes 3 de julio, 22.00 horas.
- Entrega 2: Viernes 7 de agosto, 22.00 horas.

Para la **Entrega 1** y **Entrega 2** se debe adjuntar un archivo comprimido con los siguientes elementos:

1. Base de datos procesada (es decir, la base de datos lista para la aplicación de los análisis)

2. Archivo de la entrega (que puede ser un archivo RMarkdown o Word)

    a. En el caso de entregar en formato R Markdown (.rmd) el código de los análisis deben estar incluidos en el manuscrito.
    
    b. En caso de Word (.doc) se debe incluir el RScript.

---

## Recomendaciones para el trabajo {.tabset}

### Escritura académica

- Una idea por párrafo

- Uso de "oración principal" (topic sentence): usualmente es la oración al principio del párrafo, que resume el sentido del párrafo completo y que conecta con el párrafo anterior.

- [Taller para escritura académica](https://es.scribd.com/document/454444052/Taller-para-escritura-academica)


### Ejemplos de artículos de investigación

- Con regresión simple

  - [Ortiz-Inostroza, C., & López, E. (2017). Explorando modelos estadísticos para explicar la participación en protestas en Chile. Revista de Sociología, (32), pp. 13-31. doi:10.5354/0719-529X.2017.47883](https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47883/50542
)

  - [Cereceda-Marambio, K., & Torres-Solís, A. (2017). Satisfacción con la democracia en Chile: De lo normativo a lo valorativo. Revista de Sociología, (32), pp. 32-49. doi:10.5354/0719-529X.2017.47884] (https://revistadesociologia.uchile.cl/index.php/RDS/article/view/47884/50543)


- Con regresión logística

  - [Gayo Cal, M. G., Cabrol, G. O., & Méndez, M. L. (2019). Elección escolar y selección de familias: reproducción de la clase media alta en Santiago de Chile. Revista Internacional de Sociología, 77(1), 120. https://doi.org/10.3989/ris.2019.77.1.17.310](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/1020/1338)

  - [Delfini, M. (2013) La afiliación sindical en Argentina. Análisis sobre sus determinantes. Revista Internacional de Sociología, 71(1)91-114,  http://dx.doi.org/10.3989/ris.2012.01.24.](http://revintsociologia.revistas.csic.es/index.php/revintsociologia/article/view/485/507)

### Guías de análisis de datos

- [Flujo 1: Ajustando datos](documents/trabajos/flujo_analisis1.html)

- [Reportes dinámicos con Rmarkdown](documents/trabajos/guia_rep_dinamico/reportedinamico.html)

- [Visualización y reporte](documents/trabajos/guia_rep_dinamico/reporte_vis.html)

### Otros links

- [Imágenes en Rmarkdown](http://zevross.com/blog/2017/06/19/tips-and-tricks-for-working-with-images-and-figures-in-r-markdown-documents/#default-settings-for-including-images-and-figures-in-r-markdown)
