main:
  - name: Programa
    url: /programa/
    weight: 1
  - name: Planificación
    url: /schedule/
    weight: 2
  - name: Clases
    url: /class/
    weight: 3
  - name: Evaluaciones
    url: /reference/
    weight: 4
  - name: Material
    url: /tutorial/
    weight: 5
