---
title: "Planificación"
slug: schedule
---

|      |  <i class="fas fa-chalkboard-teacher"></i>  Contenidos y Presentaciones    |  <i class="fas fa-user-edit"></i>  Prácticas y evaluaciones | <i class="fas fa-book-reader"></i> Lecturas y material adicional
- |-----------|-----------|----------
<font color="orange"> **Unidad 1**  | **Enfoques y modelos para el análisis de la estructura social**</font>  |   |   |
19-mar | [**1.1 Introducción. Evolución de la desigualdad en Chile: fuentes para su discusión y medición actual.** <br> **1.2 Representaciones de la desigualdad y la estructura de clases**](/class/01-class) <br/> |  |  - [Ossowski, Stanislaw (1972) Estructura de clases y conciencia social, Península, Barcelona. Leer capítulos 2, 3 y 4.(p. 27-89)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
23-mar | [**1.3 Modelos de análisis de la estructura de clase** <br> **1.4 Enfoque neomarxista explotación, clase y posiciones contradictorias**](/class/02-class) <br/> |  |  -[Wright, E. O. (2015). Prefacio y De las batallas del gran paradigma al realismo pragmático: Hacia un análisis integral de las clases . En Comprender las clases sociales (pp. 7–33). Akal](/docs/lecturas/principal/U1L02.Comprender_las_clases_sociales._Erik_Olin_Wright.Prefacio-Introduccion.pdf)<br/>- [Wright, E. O. (1994) Clases, Siglo XXI, leer cap 3: “Un marco general para el análisis de clases” (p.69-116)](/docs/lecturas/principal/U1L03.Wright___Un_marco_general_para_el_an_lisis_de_clase.pdf) <br/>
2-abr   | Feriado  |   |   |
09-abr | [**1.5 Enfoque funcionalista: estratificación y desigualdad institucionalizada** <br> **1.6 Enfoque weberiano: propiedad, autoridad y clase en la sociedad industrial**](/class/03-class) <br/> |  |  - [Davis, K, Moore, W., Tulmin, M. y Wesolowski, W. (1972): "El continuo debate sobre la desigualdad", en Bendix y Lipset: Clase, status y poder, vol. I, Ed. Foessa (pp.155-170)](/docs/lecturas/principal/U1L04.Davis_y_Moore___El_continuo_debate_sobre_la_igualdad.pdf)<br>- [J. Goldthorpe (1992) “Sobre la clase de servicio, su formación y su futuro”. Zona abierta. (pp.230-261)](/docs/lecturas/principal/U1L05.Goldthorpe1992Sobrelaclasedeserviciosuformación.pdf)
16-abr | [**1.6 Enfoque neoweberiano:cierre social y reproducción de clase** <br> **1.7 Enfoque de atributos individuales: clase, consumo y distinción**](/class/04-class) <br/> |  |  - [Parkin, Frank (1984) Marxismo y teoría de clases. Una crítica burguesa. Espasa-Calpe, Madrid. cap 4: “El cierre social como exclusión” (pp.69-108)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br>- [Bourdieu, Pierre (1979): La distinción, Ed. Taurus, Leer cap. 2 (97-164)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
23-abr |  | [Entrega Ejercicio de análisis bibliográfico (1°evaluación)](/reference/#evaluacion-1) |
<font color="orange"> **Unidad 2**</font>  | <font color="orange"> **La estructura y posición social en Chile: discusiones y mediciones** </font>  |   |   |
23-abr | [**2.1 El estudio de las clases sociales y las relaciones laborales** <br> **2.2 Evolución del mercado laboral y la estructura de clases en Chile**](/class/05-class) <br/> |  |  - [Pérez Ahumada, P. (2018).  Clases sociales, sectores económicos y cambios en la estructura social chilena entre 1992 y 2013. Revista de la Cepal, N° 126, 171-192.](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
30-abr | [**2.3 .3 Mediciones de condiciones de empleo para la estratificación: propiedad, autoridad y calificación** <br> **2.4 El estudio de la estratificación y las clases medias en Chile**](/class/06-class) <br/> |  |  -[Torche, F. (2006). Una clasificación de clases para la sociedad chilena. Revista de sociología, Nº 20, 15-43.](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br/>- [Hopenhayn, M. (2010) "Clases medias en América Latina: sujeto difuso en busca de definición", en A. Bárcena & N. Serra (Editores) Clases medias y desarrollo en América Latina, CEPAL. (p.11-  36)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf) <br/>
07-mayo | [**2.5 Análisis de atributos individuales para la clasificación social: la medición de la pobreza y exclusión social** <br> **2.6 Mediciones del patrón de consumo de bienes y servicios**](/class/07-class) <br/> |  |  - [Aguilar, O. (2009) “Principios de diferenciación material y simbólica en la estratificación social”, en El arte de clasificar a los chilenos. Enfoques sobre los modelos de estratificación en Chile, Ediciones Universidad Diego Portales (P.131-152)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
21-may |  | [Entrega Ejercicio de análisis de datos (2°evaluación)](/reference/#evaluacion-2) |
<font color="orange"> **Unidad 3** </font>  | <font color="orange"> **Fenómenos asociados a la estratificación social en Chile** </font>  |   |   |
28-may | [**3.1 La estructura social a nivel subjetivo: la identidad de clase y el estatus social subjetivo**](/class/08-class) |  |  - [Elbert, R., & Pérez, P. (2018). The identity of class in Latin America: Objective class position and subjective class identification in Argentina and Chile (2009). Current Sociology, 66(5), 724–747](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br/>-[Castillo, Juan Carlos, Miranda, D., & Cabib, I. M. (2013). Todos somos de clase media: Sobre el estatus social subjetivo en Chile. Latin American Research Review, 155–173](docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
04-jun | [**3.2 La estructura social a nivel subjetivo: percepciones de conflicto, posicionamiento político, meritocracia y preferencias**](/class/09-class) <br/> |  |  -[Pérez Ahumada, P. (2013). Encontrando lo que nunca estuvo perdido. Conciencia de clase y conflicto de clases en el régimen neoliberal chileno. Revista de Sociología, 28, 83–111.](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br/>- [Castillo, Juan C., Bargsted, M., Olivos, F., & Mackenna, B. (2015). Percepción del conflicto en Chile: Un análisis desde la opinión pública, 2006-2013. En M. Castillo & C. Maldonado (Eds.), Desigualdades. Tolerancia, legitimación y conflicto en las sociedades latinoamericanas.](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf) <br/>
11-jun | [**3.3 Fenómenos asociados a la estratificación social: conflicto de clase,acción colectiva y movilidad social**](/class/10-class) <br/> |  |  - [Pérez, P. & Andrade, V. (2021) ¿Dejamos de sentirnos trabajadores? Identidad de clases en tiempos de movilización social y revitalización sindical en Chile (1999-2019). (en evaluación). DOI 10.17605/OSF.IO/PZGST](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br>-[Barozet, Espinoza & Méndez (2013) “Estratificación y movilidad social bajo un modelo neoliberal: el caso de Chile”. Revista Laboratorio.25 (p.169-191)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
18-jun | [**Asesorías para 3° evaluación y proyecto de investigación**](/class/06-class) <br/> | [Entrega Ejercicio de investigación empírica (3°evaluación)](/reference/#evaluacion-3) |
<font color="orange"> **Unidad 4** </font>  | <font color="orange"> **Desigualdades múltiples y discusiones actuales** </font>  |   |   |
25-jun | [**4.1 El enfoque de la interseccionalidad de las desigualdades: género, raza y etnia**](/class/11-class) |  |  - [Aguilar, O., Pérez, P., Ananías, R., Mora, C., y Blanco, O. (2016). Intersección entre la clase y el género y su efecto sobre la calidad del empleo en Chile. Revista de la CEPAL, N° 120, 141-161](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br/>-[Mora,‭ ‬C.‭ (‬2013‭) “‬Racialisation of Immigrants at Work:‭ ‬Labour Mobility and Segmentation of Peruvian Migrants in Chile‭”‬.‭  ‬En:‭ ‬Bulletin of Latin American Research](docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)
02-jul | [**4.2 Fenómenos recientes: la hipótesis del fin de las clases, "el precariado" y la concentración de la renta**](/class/12-class) <br/> |  |  -[Pakulski, Jan. (2015). “Fundamentos de un análisis de clases posclasista” en E. O. Wright (Editor) Modelos de análisis de clases, Tirant Humanidades, Valencia (p.211-247)](/docs/lecturas/principal/U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf)<br/>- [Wright, E.O (2015) Comprender las clases sociales. CapítuloVII "Las ambiguedades de la clase en El capital en el siglo XXI de Thomas Piketty" (p.153-167)y Capítulo IX "¿Es una clase el precariado?"(p.187-208)](/docs/lecturas/principal//U1L01.Ossowski_Estructura_de_clases_y_conciencia_social.pdf) <br/>
09-jul |  | **Presentación de estudiantes (parte de 4° evaluación)** |
16-jul |  | [Entrega Trabajo **Final** Integrativo (4°evaluación)](/reference/#evaluacion-4) |
23-jul | Cierre de acta del curso  |   |   |
